### ISSUE TITLE
Use FlutterBluePlus instead of FlutterBlue

### ISSUE THREAD

**Issue by 7arfoush** [AtzeniMichele/atmotuber#4]
This is due to the lack of maintainability of the original flutter_blue package resulting in build errors on Apple Silicon Macs.

**Comment by AtzeniMichele** [comment]
Done the update in my repo. You can now reuse this repo and close your fork ✌️

**Comment by 7arfoush** [comment]
Thanks! Can we also push this to the package?

**Comment by 7arfoush** [comment]
BTW, there were some breaking changes from migration that I fixed and just pushed to my fork.

**Comment by AtzeniMichele** [comment]
Hi, I was working on this package a month ago in the branch atmotuber 2 fixing some issue. Check also that branch Anyway, if you have done some fixes, please make a pull request so that it can be integrated
