### ISSUE TITLE
[Help]: App crash when authorize permission for Bluetooth

### ISSUE THREAD

**Issue by TakethreeSeccccc** [AtzeniMichele/atmotuber#5]
**Question:**
I was trying to build up the APK to test the Bluetooth connection to Atmotube Pro, I cloned the example and built up the APK, but it turned out that when I tapped "Connect ATMOTUBE", **the app asked me for authorize permission for Bluetooth, once I approved, the app crashed immediately**. Can you help me solve this issue? 

I think one of the reasons is that the flutter_blue_plus version used in this package is a little bit behind, the current version is updated to v1.17.3, while this package uses v1.5.2.

I also found that although the example uses flutter_blue_plus as the Bluetooth connection package, when I run the flutter pub add atmotuber in my own project, the package is still using flutter_blue.

Lastly, I would like to ask **how you tested the Bluetooth connection**.

![image](https://github.com/AtzeniMichele/atmotuber/assets/117812136/b768e243-901b-461e-b14d-162a89de2344)

For the screenshot you provided, **it is a virtual simulator or a physical device?**

Many thanks

**Comment by AtzeniMichele** [comment]
Hi @TakethreeSeccccc , to run effectively bluetooth based application, you need to build your app on physical devices :)
